#
# Copyright 2017 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: sampletenant # example - externalcspace
spec:
  sparkConf:
    spark.mapr.user.secret: mapr-user-secret-812502057
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "maprfs:///apps/spark/mycspace" # example - maprfs:///apps/spark/externalcspace
  type: Scala
  sparkVersion: "2.4.4"
  mode: cluster
  image: gcr.io/mapr-hpe/spark-2.4.4:201912180140
  imagePullPolicy: Always
  imagePullSecrets:
    - mapr-imagepull-secrets
  mainClass: com.mapr.sparkdemo.InfinityExample
  mainApplicationFile: "maprfs:///user/mapr/SparkDemo.jar"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 2.4.4
    serviceAccount: hpe-sampletenant # example - mapr-mycspace-cspace-sa
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.4
